# Generated by Django 4.2.2 on 2023-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickeyverse_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='name',
            new_name='stickername',
        ),
        migrations.AlterField(
            model_name='sticker',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(upload_to='stickeyverse_app/stickers/'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
