# Generated by Django 4.2.2 on 2023-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickeyverse_app', '0003_delete_category_alter_sticker_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='material',
            field=models.CharField(default='', max_length=150),
        ),
    ]
