# Generated by Django 4.2.2 on 2023-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickeyverse_app', '0004_sticker_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
