# Generated by Django 4.2.2 on 2023-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickeyverse_app', '0005_alter_sticker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
